# Generated by Django 5.1.3 on 2025-03-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_photos/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_qr_codes/'),
        ),
    ]
